/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PositionService } from "../position.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PositionCreateInput } from "./PositionCreateInput";
import { Position } from "./Position";
import { PositionFindManyArgs } from "./PositionFindManyArgs";
import { PositionWhereUniqueInput } from "./PositionWhereUniqueInput";
import { PositionUpdateInput } from "./PositionUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PositionControllerBase {
  constructor(
    protected readonly service: PositionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Position })
  @nestAccessControl.UseRoles({
    resource: "Position",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: PositionCreateInput,
  })
  async createPosition(
    @common.Body() data: PositionCreateInput
  ): Promise<Position> {
    return await this.service.createPosition({
      data: {
        ...data,

        comments: data.comments
          ? {
              connect: data.comments,
            }
          : undefined,
      },
      select: {
        col: true,

        comments: {
          select: {
            id: true,
          },
        },

        content: true,
        createdAt: true,
        id: true,
        line: true,
        toCol: true,
        toLine: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Position] })
  @ApiNestedQuery(PositionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Position",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async positions(@common.Req() request: Request): Promise<Position[]> {
    const args = plainToClass(PositionFindManyArgs, request.query);
    return this.service.positions({
      ...args,
      select: {
        col: true,

        comments: {
          select: {
            id: true,
          },
        },

        content: true,
        createdAt: true,
        id: true,
        line: true,
        toCol: true,
        toLine: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Position })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Position",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async position(
    @common.Param() params: PositionWhereUniqueInput
  ): Promise<Position | null> {
    const result = await this.service.position({
      where: params,
      select: {
        col: true,

        comments: {
          select: {
            id: true,
          },
        },

        content: true,
        createdAt: true,
        id: true,
        line: true,
        toCol: true,
        toLine: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Position })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Position",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: PositionUpdateInput,
  })
  async updatePosition(
    @common.Param() params: PositionWhereUniqueInput,
    @common.Body() data: PositionUpdateInput
  ): Promise<Position | null> {
    try {
      return await this.service.updatePosition({
        where: params,
        data: {
          ...data,

          comments: data.comments
            ? {
                connect: data.comments,
              }
            : undefined,
        },
        select: {
          col: true,

          comments: {
            select: {
              id: true,
            },
          },

          content: true,
          createdAt: true,
          id: true,
          line: true,
          toCol: true,
          toLine: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Position })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Position",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePosition(
    @common.Param() params: PositionWhereUniqueInput
  ): Promise<Position | null> {
    try {
      return await this.service.deletePosition({
        where: params,
        select: {
          col: true,

          comments: {
            select: {
              id: true,
            },
          },

          content: true,
          createdAt: true,
          id: true,
          line: true,
          toCol: true,
          toLine: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
