/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { ActionEvent } from "./ActionEvent";
import { ActionEventCountArgs } from "./ActionEventCountArgs";
import { ActionEventFindManyArgs } from "./ActionEventFindManyArgs";
import { ActionEventFindUniqueArgs } from "./ActionEventFindUniqueArgs";
import { CreateActionEventArgs } from "./CreateActionEventArgs";
import { UpdateActionEventArgs } from "./UpdateActionEventArgs";
import { DeleteActionEventArgs } from "./DeleteActionEventArgs";
import { Collection } from "../../collection/base/Collection";
import { Document } from "../../document/base/Document";
import { ActionEventService } from "../actionEvent.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ActionEvent)
export class ActionEventResolverBase {
  constructor(
    protected readonly service: ActionEventService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ActionEvent",
    action: "read",
    possession: "any",
  })
  async _actionEventsMeta(
    @graphql.Args() args: ActionEventCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ActionEvent])
  @nestAccessControl.UseRoles({
    resource: "ActionEvent",
    action: "read",
    possession: "any",
  })
  async actionEvents(
    @graphql.Args() args: ActionEventFindManyArgs
  ): Promise<ActionEvent[]> {
    return this.service.actionEvents(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ActionEvent, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ActionEvent",
    action: "read",
    possession: "own",
  })
  async actionEvent(
    @graphql.Args() args: ActionEventFindUniqueArgs
  ): Promise<ActionEvent | null> {
    const result = await this.service.actionEvent(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ActionEvent)
  @nestAccessControl.UseRoles({
    resource: "ActionEvent",
    action: "create",
    possession: "any",
  })
  async createActionEvent(
    @graphql.Args() args: CreateActionEventArgs
  ): Promise<ActionEvent> {
    return await this.service.createActionEvent({
      ...args,
      data: {
        ...args.data,

        collection: args.data.collection
          ? {
              connect: args.data.collection,
            }
          : undefined,

        document: args.data.document
          ? {
              connect: args.data.document,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ActionEvent)
  @nestAccessControl.UseRoles({
    resource: "ActionEvent",
    action: "update",
    possession: "any",
  })
  async updateActionEvent(
    @graphql.Args() args: UpdateActionEventArgs
  ): Promise<ActionEvent | null> {
    try {
      return await this.service.updateActionEvent({
        ...args,
        data: {
          ...args.data,

          collection: args.data.collection
            ? {
                connect: args.data.collection,
              }
            : undefined,

          document: args.data.document
            ? {
                connect: args.data.document,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ActionEvent)
  @nestAccessControl.UseRoles({
    resource: "ActionEvent",
    action: "delete",
    possession: "any",
  })
  async deleteActionEvent(
    @graphql.Args() args: DeleteActionEventArgs
  ): Promise<ActionEvent | null> {
    try {
      return await this.service.deleteActionEvent(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Collection, {
    nullable: true,
    name: "collection",
  })
  @nestAccessControl.UseRoles({
    resource: "Collection",
    action: "read",
    possession: "any",
  })
  async getCollection(
    @graphql.Parent() parent: ActionEvent
  ): Promise<Collection | null> {
    const result = await this.service.getCollection(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Document, {
    nullable: true,
    name: "document",
  })
  @nestAccessControl.UseRoles({
    resource: "Document",
    action: "read",
    possession: "any",
  })
  async getDocument(
    @graphql.Parent() parent: ActionEvent
  ): Promise<Document | null> {
    const result = await this.service.getDocument(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
