/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumActionEventAction } from "./EnumActionEventAction";
import { IsEnum, IsOptional, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { CollectionWhereUniqueInput } from "../../collection/base/CollectionWhereUniqueInput";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { DocumentWhereUniqueInput } from "../../document/base/DocumentWhereUniqueInput";
import { StringFilter } from "../../util/StringFilter";

@InputType()
class ActionEventWhereInput {
  @ApiProperty({
    required: false,
    enum: EnumActionEventAction,
  })
  @IsEnum(EnumActionEventAction)
  @IsOptional()
  @Field(() => EnumActionEventAction, {
    nullable: true,
  })
  action?:
    | "Download"
    | "Upload"
    | "Edit"
    | "Delete"
    | "AddRole"
    | "RemoveRole"
    | "Duplicate"
    | "Comment"
    | "Share"
    | "Assign"
    | "Star"
    | "Public"
    | "Private";

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  actor?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  assignee?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  assigner?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => CollectionWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CollectionWhereUniqueInput)
  @IsOptional()
  @Field(() => CollectionWhereUniqueInput, {
    nullable: true,
  })
  collection?: CollectionWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  createdAt?: DateTimeFilter;

  @ApiProperty({
    required: false,
    type: () => DocumentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DocumentWhereUniqueInput)
  @IsOptional()
  @Field(() => DocumentWhereUniqueInput, {
    nullable: true,
  })
  document?: DocumentWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;
}

export { ActionEventWhereInput as ActionEventWhereInput };
