/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ActionEventCreateNestedManyWithoutDocumentsInput } from "./ActionEventCreateNestedManyWithoutDocumentsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  IsBoolean,
  IsInt,
} from "class-validator";
import { Type } from "class-transformer";
import { ArchivedCreateNestedManyWithoutDocumentsInput } from "./ArchivedCreateNestedManyWithoutDocumentsInput";
import { DocumentCreateNestedManyWithoutDocumentsInput } from "./DocumentCreateNestedManyWithoutDocumentsInput";
import { CommentCreateNestedManyWithoutDocumentsInput } from "./CommentCreateNestedManyWithoutDocumentsInput";
import { MemberCreateNestedManyWithoutDocumentsInput } from "./MemberCreateNestedManyWithoutDocumentsInput";

@InputType()
class DocumentCreateInput {
  @ApiProperty({
    required: false,
    type: () => ActionEventCreateNestedManyWithoutDocumentsInput,
  })
  @ValidateNested()
  @Type(() => ActionEventCreateNestedManyWithoutDocumentsInput)
  @IsOptional()
  @Field(() => ActionEventCreateNestedManyWithoutDocumentsInput, {
    nullable: true,
  })
  actionEvents?: ActionEventCreateNestedManyWithoutDocumentsInput;

  @ApiProperty({
    required: true,
    type: () => ArchivedCreateNestedManyWithoutDocumentsInput,
  })
  @ValidateNested()
  @Type(() => ArchivedCreateNestedManyWithoutDocumentsInput)
  @IsOptional()
  @Field(() => ArchivedCreateNestedManyWithoutDocumentsInput, {
    nullable: true,
  })
  archiveds?: ArchivedCreateNestedManyWithoutDocumentsInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  authorId!: string;

  @ApiProperty({
    required: true,
    type: () => DocumentCreateNestedManyWithoutDocumentsInput,
  })
  @ValidateNested()
  @Type(() => DocumentCreateNestedManyWithoutDocumentsInput)
  @IsOptional()
  @Field(() => DocumentCreateNestedManyWithoutDocumentsInput, {
    nullable: true,
  })
  childDocuments?: DocumentCreateNestedManyWithoutDocumentsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  collectionId?: string | null;

  @ApiProperty({
    required: false,
    type: () => CommentCreateNestedManyWithoutDocumentsInput,
  })
  @ValidateNested()
  @Type(() => CommentCreateNestedManyWithoutDocumentsInput)
  @IsOptional()
  @Field(() => CommentCreateNestedManyWithoutDocumentsInput, {
    nullable: true,
  })
  comments?: CommentCreateNestedManyWithoutDocumentsInput;

  @ApiProperty({
    required: false,
    type: () => DocumentCreateNestedManyWithoutDocumentsInput,
  })
  @ValidateNested()
  @Type(() => DocumentCreateNestedManyWithoutDocumentsInput)
  @IsOptional()
  @Field(() => DocumentCreateNestedManyWithoutDocumentsInput, {
    nullable: true,
  })
  documents?: DocumentCreateNestedManyWithoutDocumentsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  emoji?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isFullWidth?: boolean | null;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isPublic!: boolean;

  @ApiProperty({
    required: true,
    type: () => MemberCreateNestedManyWithoutDocumentsInput,
  })
  @ValidateNested()
  @Type(() => MemberCreateNestedManyWithoutDocumentsInput)
  @IsOptional()
  @Field(() => MemberCreateNestedManyWithoutDocumentsInput, {
    nullable: true,
  })
  members?: MemberCreateNestedManyWithoutDocumentsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  revision?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  templateId?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  text?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  title!: string;
}

export { DocumentCreateInput as DocumentCreateInput };
