/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ActionEventUpdateManyWithoutCollectionsInput } from "./ActionEventUpdateManyWithoutCollectionsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  IsBoolean,
} from "class-validator";
import { Type } from "class-transformer";
import { ArchivedUpdateManyWithoutCollectionsInput } from "./ArchivedUpdateManyWithoutCollectionsInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { MemberUpdateManyWithoutCollectionsInput } from "./MemberUpdateManyWithoutCollectionsInput";

@InputType()
class CollectionUpdateInput {
  @ApiProperty({
    required: false,
    type: () => ActionEventUpdateManyWithoutCollectionsInput,
  })
  @ValidateNested()
  @Type(() => ActionEventUpdateManyWithoutCollectionsInput)
  @IsOptional()
  @Field(() => ActionEventUpdateManyWithoutCollectionsInput, {
    nullable: true,
  })
  actionEvents?: ActionEventUpdateManyWithoutCollectionsInput;

  @ApiProperty({
    required: false,
    type: () => ArchivedUpdateManyWithoutCollectionsInput,
  })
  @ValidateNested()
  @Type(() => ArchivedUpdateManyWithoutCollectionsInput)
  @IsOptional()
  @Field(() => ArchivedUpdateManyWithoutCollectionsInput, {
    nullable: true,
  })
  archiveds?: ArchivedUpdateManyWithoutCollectionsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  authorId?: string;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  canShare?: boolean | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  childCollectionIds?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  downloadPermission?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  icon?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  index?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isSaving?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => MemberUpdateManyWithoutCollectionsInput,
  })
  @ValidateNested()
  @Type(() => MemberUpdateManyWithoutCollectionsInput)
  @IsOptional()
  @Field(() => MemberUpdateManyWithoutCollectionsInput, {
    nullable: true,
  })
  members?: MemberUpdateManyWithoutCollectionsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  parentCollectionId?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  url?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  workspaceId?: string | null;
}

export { CollectionUpdateInput as CollectionUpdateInput };
