/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ActionEventCreateNestedManyWithoutCollectionsInput } from "./ActionEventCreateNestedManyWithoutCollectionsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  IsBoolean,
} from "class-validator";
import { Type } from "class-transformer";
import { ArchivedCreateNestedManyWithoutCollectionsInput } from "./ArchivedCreateNestedManyWithoutCollectionsInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { MemberCreateNestedManyWithoutCollectionsInput } from "./MemberCreateNestedManyWithoutCollectionsInput";

@InputType()
class CollectionCreateInput {
  @ApiProperty({
    required: false,
    type: () => ActionEventCreateNestedManyWithoutCollectionsInput,
  })
  @ValidateNested()
  @Type(() => ActionEventCreateNestedManyWithoutCollectionsInput)
  @IsOptional()
  @Field(() => ActionEventCreateNestedManyWithoutCollectionsInput, {
    nullable: true,
  })
  actionEvents?: ActionEventCreateNestedManyWithoutCollectionsInput;

  @ApiProperty({
    required: true,
    type: () => ArchivedCreateNestedManyWithoutCollectionsInput,
  })
  @ValidateNested()
  @Type(() => ArchivedCreateNestedManyWithoutCollectionsInput)
  @IsOptional()
  @Field(() => ArchivedCreateNestedManyWithoutCollectionsInput, {
    nullable: true,
  })
  archiveds?: ArchivedCreateNestedManyWithoutCollectionsInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  authorId!: string;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  canShare?: boolean | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  childCollectionIds?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  downloadPermission!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  icon?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  index?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isSaving?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => MemberCreateNestedManyWithoutCollectionsInput,
  })
  @ValidateNested()
  @Type(() => MemberCreateNestedManyWithoutCollectionsInput)
  @IsOptional()
  @Field(() => MemberCreateNestedManyWithoutCollectionsInput, {
    nullable: true,
  })
  members?: MemberCreateNestedManyWithoutCollectionsInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  parentCollectionId?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  url?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  workspaceId?: string | null;
}

export { CollectionCreateInput as CollectionCreateInput };
