/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, ValidateNested, IsOptional, IsEnum } from "class-validator";
import { DocumentWhereUniqueInput } from "../../document/base/DocumentWhereUniqueInput";
import { Type } from "class-transformer";
import { CommentWhereUniqueInput } from "./CommentWhereUniqueInput";
import { PositionWhereUniqueInput } from "../../position/base/PositionWhereUniqueInput";
import { CommentCreateNestedManyWithoutCommentsInput } from "./CommentCreateNestedManyWithoutCommentsInput";
import { EnumCommentStatus } from "./EnumCommentStatus";

@InputType()
class CommentCreateInput {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  content!: string;

  @ApiProperty({
    required: false,
    type: () => DocumentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DocumentWhereUniqueInput)
  @IsOptional()
  @Field(() => DocumentWhereUniqueInput, {
    nullable: true,
  })
  document?: DocumentWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => CommentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CommentWhereUniqueInput)
  @IsOptional()
  @Field(() => CommentWhereUniqueInput, {
    nullable: true,
  })
  parentComment?: CommentWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => PositionWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PositionWhereUniqueInput)
  @IsOptional()
  @Field(() => PositionWhereUniqueInput, {
    nullable: true,
  })
  position?: PositionWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => CommentCreateNestedManyWithoutCommentsInput,
  })
  @ValidateNested()
  @Type(() => CommentCreateNestedManyWithoutCommentsInput)
  @IsOptional()
  @Field(() => CommentCreateNestedManyWithoutCommentsInput, {
    nullable: true,
  })
  replies?: CommentCreateNestedManyWithoutCommentsInput;

  @ApiProperty({
    required: false,
    enum: EnumCommentStatus,
  })
  @IsEnum(EnumCommentStatus)
  @IsOptional()
  @Field(() => EnumCommentStatus, {
    nullable: true,
  })
  status?: "Done" | "Todo" | "Doing" | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  userId!: string;
}

export { CommentCreateInput as CommentCreateInput };
